export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_EMAIL: '/verify-email',
  PROFILE: (username: string = ':username') => `/profile/${username}`,
  FOLLOWERS: (username: string = ':username') => `/profile/${username}/followers`,
  FOLLOWING: (username: string = ':username') => `/profile/${username}/following`,
  POST_DETAIL: (id: string = ':postId') => `/post/${id}`,
  NOTIFICATIONS: '/notifications',
  SEARCH: '/search',
  MESSAGES: '/messages',
  CHAT: (id: string = ':conversationId') => `/messages/${id}`,
  BOOKMARKS: '/bookmarks',
  SETTINGS: '/settings',
  SETTINGS_ACCOUNT: '/settings/account',
  SETTINGS_PRIVACY: '/settings/privacy',
  SETTINGS_THEME: '/settings/theme',
  SETTINGS_SECURITY: '/settings/security',
} as const;
